### ISSUE TITLE
Conduit returning incomplete data for profiles

### ISSUE THREAD

**Issue by Neppkun** [calamity-inc/browse.wf#39]
This *can* be considered a dupe of #38 but that issue was closed by the author with no information, so I'm opening another issue.

When creating a request to view profile data, conduit only returns the following:
```
{
    "platform": "pc"
}
```

**Comment by Sainan** [comment]
Sorry, it seems this was a caching misconfiguration. Should be fixed now.

**Comment by Neppkun** [comment]
Trying with IDs not previously tried and the issue persists.

<img width="1010" height="235" alt="Image" src="https://github.com/user-attachments/assets/ca6d7cc6-2c07-4492-9a96-55ed939885fa" />

**Comment by Sainan** [comment]
I guess there's some sort of rate limiting or IP block in effect. Feel free to follow the 'redirect' given.

**Comment by Neppkun** [comment]
Appreciate it <3

**Comment by Sainan** [comment]
Updated the UI to accept JSON upload as per #40
